// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs9AQx74ABLD8KQDYuj3uXvIBz0r2OTEs',
    appId: '1:35673142221:web:052ae412da232a920bca84',
    messagingSenderId: '35673142221',
    projectId: 'connect-app-4a54f',
    authDomain: 'connect-app-4a54f.firebaseapp.com',
    storageBucket: 'connect-app-4a54f.firebasestorage.app',
    measurementId: 'G-P063HQZRTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzErDisbcnG5DKb2pH7lUCFIyv-8qB3lY',
    appId: '1:35673142221:android:cf414f19915d43990bca84',
    messagingSenderId: '35673142221',
    projectId: 'connect-app-4a54f',
    storageBucket: 'connect-app-4a54f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs9AQx74ABLD8KQDYuj3uXvIBz0r2OTEs',
    appId: '1:35673142221:web:052ae412da232a920bca84',
    messagingSenderId: '35673142221',
    projectId: 'connect-app-4a54f',
    authDomain: 'connect-app-4a54f.firebaseapp.com',
    storageBucket: 'connect-app-4a54f.firebasestorage.app',
    measurementId: 'G-P063HQZRTL',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrSd2GCXw6FK8PkYPr76Jpx9c8U_Zac9c',
    appId: '1:35673142221:ios:23940392df1d922a0bca84',
    messagingSenderId: '35673142221',
    projectId: 'connect-app-4a54f',
    storageBucket: 'connect-app-4a54f.firebasestorage.app',
    iosBundleId: 'com.example.connectapp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrSd2GCXw6FK8PkYPr76Jpx9c8U_Zac9c',
    appId: '1:35673142221:ios:23940392df1d922a0bca84',
    messagingSenderId: '35673142221',
    projectId: 'connect-app-4a54f',
    storageBucket: 'connect-app-4a54f.firebasestorage.app',
    iosBundleId: 'com.example.connectapp',
  );

}