import 'package:get/get_navigation/src/root/internacionalization.dart';

class Language extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'welcome_back': 'Welcome Back !',
          'we_earned': 'We earned',
          'begniners': 'Begniners!',
          'membership': 'Membership',
          'course': 'Enrolled Courses',
          'creator_courses': 'Your courses',
          'explore': 'Explorer',
          'see_all': 'See All',
          'forget_password': 'Forgot Password?',
          'login_now': 'Sign in',
          'signup_with_google': 'Signup With Google',
          'login_with_google': 'Login With Google',
          'dont_have_account': "Don't have an account ?",
          'signup': 'Signup',
          'please_enter': 'Please Enter Your Display Name',
          'please_enter_email': 'Please Enter Your Email Address',
          'please_enter_password': 'Please Enter Your Password',
          'create_account': 'Create account',
          'enter_name': 'Display name',
          'enter_email': 'someone@email.com',
          'enter_password': 'Password',
          'schedule_meeting': 'Schedule Meeting',
          'login_view': 'Log in to your account',
          'email_address': 'Email Address',
          'create': 'Continue',
          'already': 'Already have an account ?',
          'login': 'Login',
          'upcoming_event': 'Upcoming Event',
          'event': 'Revolutionizing Training: The\nLMS Project Launch',
          'continue_watching': 'Continue Watching',
          'home': 'Home',
          'messages': 'Chats',
          'clip': 'Clips',
          'spaces': 'Space',
          'creator_spaces': 'Your Spaces',
          'notification': 'Notification',
          'setting': 'Settings',
          'edit': 'Edit',
          'add_debit_credit_card': 'Add debit OR credit card',
          'add_card': 'Continue Payment ',
          'select_language': 'Select Language',
          'english': 'English',
          'english_subtitle': 'English (US)',
          'hindi': 'Hindi',
          'hindi_subtitle': 'Hindi (India)',
          'urdu': 'Urdu',
          'urdu_subtitle': 'Urdu (Pakistan)',
          'language': 'Language',
          //*********************new design content from here *********************************************/
          'chats': 'Chats',
          'ranking': 'Rankings',
          'leaderboard': 'View Full Leaderboard',
          'verification': 'Verification Code',
          'verify_otp': 'Verify OTP',

// *********************************from here is the course***********************************************/
          'your_progress': 'Your Progress',
          'next_level': 'Next level',
          'level': 'Level',
          'streak': 'Streak',
          'xp': 'XP',
          '14_days': '14 days',
          'quick_access': ' Quick Access',
          'featured_courses': 'Featured Courses',
          'top_learners': 'Top Learners',
          'view_rank': 'View Ranks',
          'recent_activity': 'Recent Activites',
          'welcome_text': 'Enter your credentials to access your account',
          'signup_text': 'Enter your details to create your CONNECT account',
          'otp_verification_text':
              'We have sent an email to your email\naccount with a verification code!',
          'x_p': 'XP Points and Badges',
          'x_p_desc1':
              'We collect and use your basic profile and activity data (such as completed lessons, XP earned, and badges achieved) to personalize your learning experience and reward your progress.',
          'x_p_desc2':
              'Your XP points and badges are securely stored and are only visible to you unless you choose to share them.We do not sell or share your achievement data with any third parties for advertising purposes.',
          'x_p_desc3':
              'You have full control over your XP and badge information and can manage your preferences in the app settings at any time.',

          'information': 'Information We Collect',
          'information1': 'To track your XP points and badges, we may collect:',
          'information2':
              'Your user ID or profile information (e.g., name, email address)',
          'information3':
              'Your progress data (e.g., completed lessons, activities, scores)',
          'information4':
              'Your achievements (e.g., earned badges, XP milestones)',
          'data_storage': 'Data Storage and Protection',
          'data_storage1':
              'Your XP and badge information is securely stored in our databases.',
          'data_storage2':
              'We implement standard security measures to prevent unauthorized access.',
          'data_storage3':
              'Only authorized CONNECT personnel can access achievement data for system maintenance.',
          'achievement': 'Sharing of Achievement Data',
          'achievement1':
              'We do not sell or share your XP or badge data with third-party advertisers.',
          'achievement2':
              'We may share achievement summaries internally (e.g., leaderboards) only if you opt-in.',
          'acceptance': 'Acceptance of Terms',
          'acceptance1':
              'By using the CONNECT mobile app, you agree to these Terms of Service and our Privacy Policy. If you do not agree, please do not use the app.',

          'user_account': 'User Account',
          'user_account1':
              'To access features like earning XP points and badges, you must create an account. You are responsible for keeping your login information secure.',

          'x_p_points': ' XP Points and Badges',
          'x_p_points1':
              'XP points and badges are earned through participation in activities like lessons, quizzes, and challenges.They are non-transferable, have no cash value, and are intended for motivational and recognition purposes within the app only.',
          'x_p_points2':
              'CONNECT reserves the right to adjust or remove XP points and badges if necessary to maintain fairness or correct errors.',
          'use_of_the_app': 'Use of the App',
          'terms_and_service': 'Terms and service',
          'terms_desc':
              'You agree to use the CONNECT app for lawful purposes only.\n\nYou must not misuse the app, disrupt its services, or attempt to access other users’ data.',
          'content_ownership': 'Content Ownership',
          'content_desc':
              "All content within the CONNECT app — including lessons, badges, designs, and trademarks — is owned by CONNECT or its partners.\n\nYou may not copy, distribute, or reuse app materials without permission.",
          'modification_update': 'Modifications and Updates',
          'modification_desc':
              'We may update or change these Terms at any time.\n\nWhen we do, we will notify you through the app or by email. Continuing to use the app means you accept the updated Terms.',
          'termination': 'Termination',
          'termination_desc':
              'We reserve the right to suspend or terminate your access to the app if you violate these Terms or misuse the platform.',
          'name': 'Name',
          'email': 'Email',
          'description': 'Description',
          'description_text': 'Please provide a brief description of the issue',
          'report_an_issue': 'Report and issue',
          'issue_desc':
              'Please describe the issue you faced so we can help fix it quickly.',
          'select_issue_type': 'Select Issue Type',
          'select_issue': 'Select issue',
          'submit': 'Submit',
          'payment_failed': 'Payment Failed',
          'payment_deducted_no_confirmation':
              'Payment Deducted but No Confirmation',
          'app_crash_checkout': 'App Crash on Checkout',
          'general': 'General',
          'push_notification': 'Creator Mode',
          'email_notification': 'Email Notification',
          'chat_notification': 'Chat Notification',
          'course_update': 'Course Updates',
          'change_password': 'Change Password',
          '2fa_enable': 'Enable 2FA',
          '2fa_disable': 'Disable 2FA',
          'privacy_policy': 'Privacy Policy',
          "terms_of_service": 'Terms of Service',

          'logout': 'Log Out',
          'privacy_security': 'Privacy & Security',
          'help_support': 'Help & Support',
          'about_us': 'About Us',
          'appearences': 'Appearances',
          'select_theme': 'Select Theme',
          'light_mode': 'Light Mode',
          'dark_mode': 'Dark Mode',
          'contact_us': 'Contact Us',
          'enter_old_password': 'Enter your old password',
          'enter_new_password': 'Enter your new password',
          'password_change': 'Password change successfully',
          'sucess': 'Success',
          'trending_course': 'Trending Course',
          'course_activity': 'Courses Activity',
          'today': 'Today',
          'yesterday': 'Yesterday',
          'all_12': 'All',
          'unread': 'Unread',
          'about': 'About',
          'stats': 'Stats',
          'achievements': 'Achievements',
          'bio': 'Bio',
          'bio_desc': 'Exploring the Connect App one step at a time.',
          'phone': 'Phone',
          'member_since': 'Member Since',
          'edit_profile': 'Edit Profile',
          'profile_photo': 'Profile Photo',
          'full_name': 'Full Name',
          'gender': 'Gender',
          'minimum_size': 'Minimum Size of 1 Mb, JPG, PNG',
          'upload_photo': 'Upload Photo',
          'edit_name': 'Edit your name',
          'edit_email': 'Edit your email',
          'edit_gender': 'Edit your gender',
          'update': 'Update',
          'profile_update': 'Profile Update Sucessfully',
          'profile': 'Profile',
          'choose_image_source': 'Choose Image Source',
          'gallery': 'Gallery',
          'camera': 'Camera',
          'User registered successfully': 'User registered successfully',
          'Success': 'Success',
          'Error': 'Error',
          'User logged in successfully': 'User logged in successfully',
          'sure_logout': 'Are you sure you want to logout?',
          'Welcome': 'Welcome',
          'coins': 'Coins',
          'wallet': 'Wallet',
          'search_here': 'Search Here',
          'enrolled_courses': 'Enrolled Courses',
          'refer': 'Refer Friends & earn',
          'enhance_security': 'Enhance your account security',
          'two_factor': 'What is Two-Factor Authentication?',
          'what_is_two_factor':
              'Two-factor authentication adds an extra layer of security to your account by requiring both your password and a verification code from your authenticator app.',
          'proceed_to_setup': 'Proceed to Setup',
          'cancel_setup': 'Cancel setup',
          'account_security': 'Account Security',
          'enable_2fa':
              'Enable 2FA to secure your account with an authenticator app.',
          'two_fa':
              'Two-factor authentication adds an extra layer of security to your account by requiring both your password and a verification code from your authenticator app.',

          'enable': 'Enable 2FA',
          '2fa_selection': '2FA Method Selection',
          'choose_2fa': 'Choose your verification method',
          'continue': 'Continue',
          'scan_qr': 'Scan QR Code',
          'scan_qr_desc': 'Scan this QR code with your authenticator app',
          'next': 'Next',
          'email_verification': 'Email Verification Setup',
          'send_code': 'We\'ll send a verification code to your email address',
          'back': 'back',
          'cant_access':
              'Cant access your authenticator app?\nUse recovery code',
          'verify': 'Verify',
          'enter_6_digit': 'Please enter a valid 6-digit code',
          'verification_code': 'Verification code ',
          'enter_6': 'Enter the 6-digit code from your',
          'forget_password_des':
              'Recover your password if you have\nforgotten the password!',
          'create_new_password': 'Create your new password',
          'set_up_password':
              'Set your new password to login into\nyour account!',
          'confirm': 'Confirm',
          'authenticator_verification': 'Authenticator Verification',
          'login_code': 'Enter 6-Digit code from your Authenticator app',
          'veryfying': 'Verifying...',
          'creator_course_progress': 'Your Courses',
          'two_factor_authentication': 'Two factor Authentication',
          'enter_username': 'Username',
          'please_enter_username': 'Please Enter Your Username',
          'enter_at_least_3_characters': 'Enter atleast 3 character',
          'username_available': 'Available',
          'courses': 'All Courses',
          'nav_course': 'Courses',
          'change_avatar': 'Change Avatar',
          'view_all': 'View All',
          'creator': ' Become Creator',
          'display_name': 'Display name',
          'user_name': 'User Name',
          'your_position': 'Your Position',
          'edit_bio': 'Edit Bio',
        },
        'hi_IN': {
          'clip': 'क्लिप',
          'edit_bio': 'बायो संपादित करें',
          'your_position': 'आपकी रैंक',
          'user_name': 'उपयोगकर्ता नाम',
          'display_name': 'प्रदर्शित होने वाला नाम',
          'creator': 'निर्माता बनें',
          'view_all': 'सभी देखें',
          'change_avatar': 'अवतार बदले ',
          'nav_course': 'कोर्स',
          'username_available': 'उपलब्ध',
          'enter_at_least_3_characters': 'कम से कम 3 अक्षर दर्ज करें',
          'enter_username': 'अपना उपयोगकर्ता नाम दर्ज करें ',
          'please_enter_username': 'क्रपया अपना उपयोगकर्ता नाम दर्ज करें',
          'creator_courses': 'आपके कोर्स',
          'creator_course_progress': 'आपके कोर्स',
          'veryfying': 'सत्यापन किया जा रहा है...',
          'login_code': 'अपने प्रमाणक ऐप से 6-अंकीय कोड दर्ज करें',
          'authenticator_verification': 'प्रमाणक सत्यापन',
          'confirm': 'पुष्टि करना',
          'set_up_password':
              'अपने खाते में लॉगइन करने के लिए अपना नया पासवर्ड सेट करें!',
          'create_new_password': 'अपना नया पासवर्ड बनाएं',
          'forget_password_des':
              'यदि आप पासवर्ड भूल गए हैं तो अपना पासवर्ड पुनः प्राप्त करें!',
          'enter_6': 'अपने खाते से 6 अंकों का कोड दर्ज करें',
          'verification_code': 'सत्यापन कोड',
          'enter_6_digit': 'कृपया वैध 6-अंकीय कोड दर्ज करें',
          'verify': 'सत्यापित करें',
          'cant_access':
              'अपने प्रमाणक ऐप तक नहीं पहुंच पा रहे हैं?\nपुनर्प्राप्ति कोड का उपयोग करें',
          'back': 'पीछे',
          'send_code': 'हम आपके ईमेल पते पर एक सत्यापन कोड भेजेंगे',
          'email_verification': 'ईमेल सत्यापन सेटअप',
          'next': 'आगे बढ़े',
          'scan_qr_desc': 'अपने प्रमाणक ऐप से इस QR कोड को स्कैन करें',
          'scan_qr': 'स्कैन क्यू आर कोड',
          'continue': 'आगे बढ़े ',
          'choose_2fa': 'अपनी सत्यापन विधि चुनें',
          '2fa_selection': '2FA विधि चयन',
          'enable': '2FA सक्षम करें',
          'two_fa':
              'दो-कारक प्रमाणीकरण आपके पासवर्ड और आपके प्रमाणक ऐप से प्राप्त सत्यापन कोड दोनों की आवश्यकता के द्वारा आपके खाते में सुरक्षा की एक अतिरिक्त परत जोड़ता है।',
          'enable_2fa':
              'अपने खाते को प्रमाणक ऐप से सुरक्षित करने के लिए 2FA सक्षम करें।',
          'account_security': 'खाता सुरक्षा',
          'cancel_setup': 'सेटअप रद्द करें',
          'proceed_to_setup': 'सेटअप के लिए आगे बढ़ें',
          'what_is_two_factor':
              'दो-कारक प्रमाणीकरण आपके पासवर्ड और आपके प्रमाणक ऐप से प्राप्त सत्यापन कोड दोनों की आवश्यकता के द्वारा आपके खाते में सुरक्षा की एक अतिरिक्त परत जोड़ता है।',
          'two_factor': 'दो-कारक प्रमाणीकरण क्या है?',
          'enhance_security': 'अपने खाते की सुरक्षा बढ़ाएँ',
          'refer': 'दोस्तों को रेफर करें और कमाएं',
          'enrolled_courses': 'नामांकित पाठ्यक्रम',
          'search_here': 'यहाँ खोजे',
          'wallet': 'बटुआ',
          'coins': 'सिक्के',
          'User registered successfully': 'उपयोगकर्ता सफलतापूर्वक पंजीकृत हुआ',
          'User logged in successfully': 'उपयोगकर्ता सफलतापूर्वक लॉग इन हुआ',
          'sure_logout': "क्या आप वाकई में बाहर निकलना चाहते हैं?",
          'Success': 'सफलता',
          'membership': 'सदस्यता लें',
          'Welcome': 'स्वागत',
          'Error': 'त्रुटि',
          'choose_image_source': 'छवि स्रोत चुनें',
          'gallery': 'गैलरी',
          'camera': 'कैमरा',
          'minimum_size': 'न्यूनतम आकार 1 एमबी, जेपीजी, पीएनजी',
          'upload_photo': 'फोटो अपलोड करें',
          'edit_name': 'अपना नाम संपादित करें',
          'edit_email': 'अपना ईमेल संपादित करें',
          'edit_gender': 'अपना लिंग संपादित करें',
          'update': 'अपडेट करें',
          'profile_photo': 'प्रोफाइल फोटो',
          'full_name': 'पूरा नाम ',
          'gender': 'लिंग',
          'about': 'के बारे में',
          'stats': 'आँकड़े',
          'achievements': 'उपलब्धियाँ',
          'edit_profile': 'प्रोफाइल बदले',
          'bio': 'बायो ',
          'bio_desc': 'स्मार्ट ब्रह्मांड की खोज एक कदम एक समय पर।',
          'phone': 'फोन',
          'member_since': 'सदस्यता शुरू',
          'all_12': 'सभी',
          'unread': 'बिना पढे हुए',
          'today': ' आज ',
          'yesterday': 'बीता हुआ कल',
          'trending_course': 'लोकप्रिय पाठ्यक्रम',
          'course_activity': 'पाठ्यक्रम गतिविधि',
          'enter_old_password': 'अपना पुराना पासवर्ड दर्ज करें',
          'enter_new_password': 'अपना नया पासवर्ड दर्ज करें',
          'password_change': 'पासवर्ड सफलतापूर्वक बदल गया',
          'sucess': 'सफलता',
          'general': 'सामान्य',
          'push_notification': 'पुश सूचनाएं',
          'email_notification': 'ईमेल सूचना',
          'chat_notification': 'चैट सूचना',
          'course_update': 'पाठ्यक्रम अपडेट',
          'change_password': 'पासवर्ड बदलें',
          '2fa_enable': 'दो-कारक प्रमाणीकरण लगायें',
          '2fa_disable': 'दो-कारक प्रमाणीकरण हटाए',
          'two_factor_authentication': 'दो-कारक प्रमाणीकरण',
          'privacy_policy': 'गोपनीयता नीति',
          'terms_of_service': 'सेवा की शर्तें',
          'contact_us': 'हमसे संपर्क करें',
          'logout': 'लॉग आउट',
          'privacy_security': 'गोपनीयता और सुरक्षा',
          'help_support': 'सहायता और समर्थन',
          'about_us': 'हमारे बारे में',
          'appearences': 'दिखावट',
          'select_theme': 'थीम चुनें',
          'light_mode': 'लाइट मोड',
          'dark_mode': 'डार्क मोड',
          'payment_failed': 'भुगतान विफल',
          'payment_deducted_no_confirmation':
              'भुगतान काटा गया लेकिन पुष्टि नहीं हुई',
          'app_crash_checkout': 'चेकआउट पर ऐप क्रैश',
          'report_an_issue': 'समस्या की सूचना दें',
          'issue_desc':
              'कृपया आपके सामने आई समस्या का वर्णन करें ताकि हम इसे जल्दी ठीक कर सकें।',
          'select_issue_type': 'समस्या प्रकार चुनें',
          'select_issue': 'समस्या चुनें',
          'submit': 'जमा करें',
          'name': 'नाम',
          'email': 'ईमेल',
          'description': 'विवरण',
          'description_text': 'कृपया समस्या का संक्षिप्त विवरण प्रदान करें',
          'submit_form': 'जमा करें ',
          'use_of_the_app': 'ऐप का उपयोग',
          'terms_and_service': 'नियम और सेवा',
          'terms_desc':
              'आप CONNECT ऐप का उपयोग केवल कानूनी उद्देश्यों के लिए करने के लिए सहमत हैं।\n\nआपको ऐप का दुरुपयोग नहीं करना चाहिए, इसकी सेवाओं को बाधित नहीं करना चाहिए, या अन्य उपयोगकर्ताओं के डेटा तक पहुँचने का प्रयास नहीं करना चाहिए।',
          'content_ownership': 'सामग्री स्वामित्व',
          'content_desc':
              'CONNECT ऐप के भीतर सभी सामग्री — जिसमें पाठ, बैज, डिज़ाइन, और ट्रेडमार्क शामिल हैं — CONNECT या इसके भागीदारों के स्वामित्व में हैं।\n\nआप बिना अनुमति के ऐप सामग्री को कॉपी, वितरित, या पुनः उपयोग नहीं कर सकते।',
          'modification_update': 'संशोधन और अपडेट',
          'modification_desc':
              'हम इन शर्तों को किसी भी समय अपडेट या बदल सकते हैं।\n\nजब हम ऐसा करेंगे, तो हम आपको ऐप के माध्यम से या ईमेल द्वारा सूचित करेंगे। ऐप का उपयोग जारी रखने का मतलब है कि आपने अपडेट की गई शर्तों को स्वीकार कर लिया है।',
          'termination': 'समाप्ति',
          'termination_desc':
              'यदि आप इन शर्तों का उल्लंघन करते हैं या प्लेटफॉर्म का दुरुपयोग करते हैं, तो हम आपके ऐप तक पहुँच को निलंबित या समाप्त करने का अधिकार सुरक्षित रखते हैं।',
          'verification': 'सत्यापन कोड',
          'verify_otp': 'ओटीपी सत्यापित करें',
          'leaderboard': 'पूरा लीडरबोर्ड देखें',
          'chats': 'बातचीत',
          'ranking': 'स्थान',
          'select_language': 'भाषा चुनें',
          'english': 'अंग्रेजी',
          'english_subtitle': 'अंग्रेजी (यूएस)',
          'hindi': 'हिन्दी',
          'hindi_subtitle': 'हिन्दी (भारत)',
          'urdu': 'उर्दू',
          'urdu_subtitle': 'उर्दू (पाकिस्तान)',
          'language': 'भाषा',
          'welcome_back': 'वापस स्वागत है!',
          'we_earned': 'हमने कमाया',
          'begniners': 'शुरुआती!',
          'course': 'पाठ्यक्रम',
          'explore': 'अन्वेषण करें',
          'see_all': 'सभी देखें',
          'forget_password': 'पासवर्ड भूल गए',
          'login_now': 'अब लॉगिन करें',
          'signup_with_google': 'गूगल  के साथ साइनअप करें',
          'login_with_google': 'गूगल के साथ लॉगिन करें',
          'dont_have_account': 'खाता नहीं है?',
          'signup': 'साइनअप',
          'please_enter': 'कृपया अपना नाम दर्ज करें',
          'please_enter_email': 'कृपया अपना ईमेल पता दर्ज करें',
          'please_enter_password': 'कृपया अपना पासवर्ड दर्ज करें',
          'create_account': 'खाता बनाएं',
          'enter_name': 'अपना नाम दर्ज करें',
          'enter_email': 'अपना ईमेल पता दर्ज करें',
          'enter_password': 'अपना पासवर्ड दर्ज करें',
          'schedule_meeting': 'बैठक शेड्यूल करें',
          'login_view': 'लॉगिन दृश्य',
          'email_address': 'ईमेल पता',
          'create': 'खाता बनाएं',
          'already': 'पहले से ही खाता है ?',
          'login': 'लॉगिन',
          'courses': 'सभी कोर्स',
          'upcoming_event': 'आगामी आयोजन',
          'event': 'प्रशिक्षण में क्रांति: LMS परियोजना लॉन्च',
          'continue_watching': 'देखना जारी रखें',
          'home': 'होम',
          'messages': 'चैट',
          'creator_spaces': 'आपके स्पेस',
          'spaces': 'स्पेस',
          'notification': 'सूचनाएं',
          'setting': 'सेटिंग',
          'edit': 'संपादन',
          'add_debit_credit_card': 'डेबिट या क्रेडिट कार्ड जोड़ें',
          'add_card': 'भुगतान जारी रखें',
          'your_progress': 'आपकी प्रगति',
          'next_level': 'अगला स्तर',
          'level': 'स्तर',
          'streak': 'लकीर',
          'xp': 'XP',
          '14_days': '14 दिन',
          'quick_access': 'त्वरित पहुँच',
          'featured_courses': 'विशेष पाठ्यक्रम',
          'top_learners': 'शीर्ष शिक्षार्थी',
          'view_rank': 'रैंक देखें',
          'recent_activity': 'हाल की गतिविधियाँ',
          'welcome_text':
              'कनेक्ट में वापस स्वागत है! अपने ईमेल पते और पासवर्ड दर्ज करें ताकि कनेक्ट की नवीनतम सुविधाओं का आनंद ले सकें',
          'otp_verification_text':
              'हमने आपके ईमेल खाते पर एक सत्यापन कोड के साथ एक ईमेल भेजा है!',
          'x_p': 'XP अंक और बैज',
          'x_p_desc1':
              'हम आपकी बुनियादी प्रोफाइल और गतिविधि डेटा (जैसे पूर्ण किए गए पाठ, अर्जित XP, और प्राप्त बैज) को एकत्र और उपयोग करते हैं ताकि आपका शिक्षण अनुभव व्यक्तिगत हो और आपकी प्रगति को पुरस्कृत किया जा सके।',
          'x_p_desc2':
              'आपके XP अंक और बैज सुरक्षित रूप से संग्रहीत हैं और केवल आपके लिए दृश्यमान हैं जब तक आप उन्हें साझा करने का चयन नहीं करते। हम आपके उपलब्धि डेटा को विज्ञापन उद्देश्यों के लिए किसी तीसरे पक्ष के साथ बेचते या साझा नहीं करते।',
          'x_p_desc3':
              'आपके पास अपने XP और बैज जानकारी पर पूर्ण नियंत्रण है और आप किसी भी समय ऐप सेटिंग्स में अपनी प्राथमिकताओं को प्रबंधित कर सकते हैं।',
          'information': 'हम जो जानकारी एकत्र करते हैं',
          'information1':
              'आपके XP अंक और बैज को ट्रैक करने के लिए, हम एकत्र कर सकते हैं:',
          'information2':
              'आपका उपयोगकर्ता ID या प्रोफाइल जानकारी (उदाहरण के लिए, नाम, ईमेल पता)',
          'information3':
              'आपका प्रगति डेटा (उदाहरण के लिए, पूर्ण किए गए पाठ, गतिविधियाँ, स्कोर)',
          'information4':
              'आपकी उपलब्धियाँ (उदाहरण के लिए, अर्जित बैज, XP मील के पत्थर)',
          'data_storage': 'डेटा भंडारण और संरक्षण',
          'data_storage1':
              'आपकी XP और बैज जानकारी हमारे डेटाबेस में सुरक्षित रूप से संग्रहीत है।',
          'data_storage2':
              'हम अनधिकृत पहुँच को रोकने के लिए मानक सुरक्षा उपाय लागू करते हैं।',
          'data_storage3':
              'केवल अधिकृत CONNECT कर्मचारी सिस्टम रखरखाव के लिए उपलब्धि डेटा तक पहुँच सकते हैं।',
          'achievement': 'उपलब्धि डेटा का साझाकरण',
          'achievement1':
              'हम आपके XP या बैज डेटा को तीसरे पक्ष के विज्ञापनदाताओं के साथ बेचते या साझा नहीं करते।',
          'achievement2':
              'हम उपलब्धि सारांश को आंतरिक रूप से (उदाहरण के लिए, लीडरबोर्ड) केवल तभी साझा कर सकते हैं जब आप इसमें शामिल होने का चयन करें।',
          'acceptance': 'शर्तों की स्वीकृति',
          'acceptance1':
              'CONNECT मोबाइल ऐप का उपयोग करके, आप इन सेवा शर्तों और हमारी गोपनीयता नीति से सहमत होते हैं। यदि आप सहमत नहीं हैं, तो कृपया ऐप का उपयोग न करें।',
          'user_account': 'उपयोगकर्ता खाता',
          'user_account1':
              'XP अंक और बैज अर्जित करने जैसी सुविधाओं तक पहुँचने के लिए, आपको एक खाता बनाना होगा। आप अपने लॉगिन जानकारी को सुरक्षित रखने के लिए जिम्मेदार हैं।',
          'x_p_points': 'XP अंक और बैज',
          'x_p_points1':
              'XP अंक और बैज पाठ, क्विज़, और चुनौतियों जैसी गतिविधियों में भागीदारी के माध्यम से अर्जित किए जाते हैं। वे गैर-हस्तांतरणीय हैं, इनका कोई नकद मूल्य नहीं है, और ये केवल ऐप के भीतर प्रेरणा और मान्यता के उद्देश्यों के लिए हैं।',
          'x_p_points2':
              'CONNECT निष्पक्षता बनाए रखने या त्रुटियों को सुधारने के लिए आवश्यक होने पर XP अंक और बैज को समायोजित या हटाने का अधिकार सुरक्षित रखता है।'
        }
      };
}
